name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace Sharon-codes/Cranium_mindMap with your actual Hugging Face username/space
          git push -f https://Sharon-codes:$HF_TOKEN@huggingface.co/spaces/Sharon-codes/Cranium_mindMap main
